### ISSUE TITLE
文件没有访问权限

### ISSUE THREAD

**Issue by Yiting1009** [wdhudiekou/STSC#1]
您好，感谢您的工作！
但vggfeature.pth和UIEB pretrained model都无法下载，请问可以分享一下么，谢谢！！
<img width="635" alt="截屏2022-12-13 16 59 06" src="https://user-images.githubusercontent.com/67905589/207272916-d2ae5828-0705-4f8c-b37c-99dcf8a9f055.png">

**Comment by wdhudiekou** [comment]
非常感谢您指出的问题，我稍后会处理一下。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Tue, Dec 13, 2022 04:59 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[wdhudiekou/STSC] 文件没有访问权限 (Issue #1)

&nbsp;



 
您好，感谢您的工作！
 但vggfeature.pth和UIEB pretrained model都无法下载，请问可以分享一下么，谢谢！！

**Comment by wdhudiekou** [comment]
增加了百度云下载链接，you can try it. Thanks for your attention.

**Comment by Yiting1009** [comment]
十分感谢您的回复！！
